#config_version=6

slide_player:
  mode_yauch_started: yauch

mode:
  start_events: yauch_start
  stop_events: timer_yauch_timer_complete
  priority: 300

variable_player:
  s_left_ramp_active:
    score: 5000|block
  s_right_ramp_active:
    score: 5000|block
  timer_yauch_timer_tick:
    yauch_timer:
      int: device.timers.yauch_timer.ticks
      action: set

timers:
  yauch_timer:
    start_value: 10
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_yauch_started
      - action: add
        event: s_left_ramp_active
        value: 5
      - action: add
        event: s_right_ramp_active
        value: 5
