#config_version=6
#skillshot

#TODO: add sneak in skill shot

mode:
  start_events: ball_out
  stop_events:
    - skill_success
    - skill_failed
  priority: 500

timers:
  skillshot_timeout:
    start_value: 5
    end_value: 0
    direction: down
    tick_interval: 1s
    start_running: true
    #control_events:
    #  - action: start
    #    event: balldevice_bd_plunger_ball_eject_attempt

variable_player:
  timer_skill_shot_tick:
    int: device.timers.skill_shot_timeout.ticks
    action: set
  skill_success:
    score: 4444

state_machines:
  skillshot_success:
    debug: true
    states:
      start:
        label: Skill shot ready
      success:
        label: Skill successful
        events_when_started: skill_success
      failed:
        label: Skill failed
        events_when_started: skill_failed
    transitions:
      - source: start
        target: success
        events: captive_ball_hit
      - source: start
        target: failed
        events: timer_skillshot_timeout_complete
