#config_version=6
##! mode: miked_setup_mode

mode:
  start_events: ball_started, mode_brassmonkey_stopped
  stop_events: brassmonkey_start
  priority: 200

counters:
  brassmonkey_counter:
    count_events: s_three_bank_standup_active
    starting_count: 0
    count_complete_value: 3 * current_player.brassmonkey_modes_started + 2
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: brassmonkey_start
    debug: true
    restart_events: ball_started, mode_brassmonkey_stopped

variable_player:
  logicblock_brassmonkey_counter_updated:
    brassmonkey_count_var:
      int: value
      action: set
