#config_version=6
##! mode: base_mode

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started: base


variable_player:
  s_right_inlane_active:
    score: 100
  s_left_inlane_active:
    score: 100
  s_left_slingshot_active:
    score: 50
  s_right_slingshot_active:
    score: 50
  s_left_upper_pop_active:
    score: 25
  s_center_upper_pop_active:
    score: 25
  s_right_lower_pop_active:
    score: 25
  s_captive_ball_active:
    score: 1000
  s_pop_standup_active: 
    score: 50
  s_upper_pop_standup_active: 
    score: 50
  s_spinner_active:
    score: 3
  drop_target_bank_three_bank_down:
    score: 666
  drop_target_bottom_down:
    score: 2
  drop_target_middle_down:
    score: 3
  drop_target_top_down:
    score: 4
  s_scoop_active:
    score: 500

