#config_version=6
##! mode: base_mode

mode:
  start_events: ball_started
  priority: 100

variable_player:
  s_right_inlane_active:
    score: 100
  s_left_inlane_active:
    score: 100
  s_left_slingshot_active:
    score: 50
  s_right_slingshot_active:
    score: 50
  s_right_lower_pop_active:
    score: 25
  s_captive_ball_active:
    score: 1000
  s_spinner:
    score: 3
