#config_version=6
##! mode: base_mode

config:
  - shots_base.yaml
  - variables_base.yaml
  - sounds_base.yaml

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started: base

