#config_version=6

sound_player:
  mode_base_started:
    Randomizer:
      action: play
      fade_in: 300ms
      events_when_stopped: play_random_song
  play_random_song:
    Randomizer:
      action: play
      fade_in: 300ms
      events_when_stopped: play_random_song
  mode_brassmonkey_started:
    Randomizer:
      action: stop
    play_random_song:
      action: stop
  mode_miked_started:
    Randomizer:
      action: stop
    play_random_song:
      action: stop
