#config_version=6


sound_player:
  mode_base_started:
    brassmonkey_music:
      action: play
      #loops: -1
      bus: music
      fade_in: 300ms
      events_when_stopped: play_random_song
  play_random_song:
    Randomizer:
      action: play
      #loops: -1
      bus: music
      fade_in: 300ms
      events_when_stopped: play_random_song
  mode_base_stopped:
    Randomizer:
      action: stop
    play_random_song:
      action: stop
    brassmonkey_music:
      action: stop
  mode_brassmonkey_start:
    Randomizer:
      action: stop
    play_random_song:
      action: stop
    brassmonkey_music:
      action: play
      bus: music
      fade_in: 300ms
      events_when_stopped: play_random_song
