#config_version=6
##! mode: miked_setup_mode

mode:
  start_events: ball_started, mode_adrock_stopped
  stop_events: adrock_start
  priority: 200

counters:
  adrock_counter:
    count_events: s_three_bank_standup_active
    starting_count: 0
    count_complete_value: 3
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: adrock_start
    debug: true
    restart_events: ball_started, mode_adrock_stopped

variable_player:
  logicblock_adrock_counter_updated:
    adrock_count_var:
      int: value
      action: set
