#config_version=6
##! mode: miked_mode

# This mode should end when the player gets down to one ball
# But not during the shoot_again period.

slide_player:
  mode_brassmonkey_started: brassmonkey

mode:
  start_events: brassmonkey_start
  stop_events: multiball_brassmonkey_ended
  priority: 400

counters:
  brassmonkey_jackpot_counter:
    count_events: ramps_hit, orbits_hit
    starting_count: 0
    count_complete_value: 5
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: brassmonkey_jackpot_start
    restart_events: mode_brassmonkey_jackpot_stopped
    debug: true

variable_player:
  three_bank_standup_hit:
    score: current_player.brassmonkey_multiplier * 5000|block
  ramps_hit:
    score: current_player.brassmonkey_multiplier * 1000|block
  orbits_hit:
    score: current_player.brassmonkey_multiplier * 1000|block

sound_player:
  mode_brassmonkey_started:
    brassmonkey_music:
      action: play
      bus: music
      fade_in: 300ms
      events_when_stopped: play_random_song
# when we get lights, light all ramps and orbits
# light super jackpot flashing on 5th ramp/orbit
# jackpots are ramps and orbits
# after 5 of any, innerloop is super jackpot
# and ramps and orbits no longer jackpots

# if you hit super jackpot, double all scores and start again

# Brass monkey SETUP mode:
# knock all 3 drop targets down, lights an insert, knock all 3 down again, light another insert, ...
# 2x, 3x, 5x multiplier for brass monkey mode, can I round?
# v1, might be 2,3,4
# reset for every multiball
