#config_version=6
##! mode: miked_mode

# This mode should end when the player gets down to one ball
# But not during the shoot_again period.

slide_player:
  mode_brassmonkey_started: brassmonkey

mode:
  start_events: brassmonkey_start
  stop_events: multiball_brassmonkey_ended
  priority: 400

variable_player:
  s_three_bank_standup_active:
    score: 5000|block
# jackpots are ramps and orbits
# after 5 of any, innerloop is super jackpot
# and ramps and orbits no longer jackpots

# Brass monkey SETUP mode:
# knock all 3 drop targets down, lights an insert, knock all 3 down again, light another insert, ...
# 2x, 3x, 5x multiplier for brass monkey mode, can I round?
# v1, might be 2,3,4
# reset for every multiball
