#config_version=6

# mike is using this for the numbers
# https://fastpinball.com/cookbook/lower-third/
# https://fastpinball.com/mpf/config/net/

hardware:
  platform: fast
  driverboards: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024
        order: 1
      "3208":
        model: FP-I/O-3208
        order: 2

switches:
  s_left_flipper:
    number: cab-8
    tags: left_flipper
  s_right_flipper:
    number: cab-9
    tags: right_flipper
  s_start:
    number: cab-11
    tags: start
  #s_top_right_flipper:
  #  number: cab-10
  #  tags: top_right_flipper

coils:
  c_flipper_left_main:
    number: 3208-3
    default_pulse_ms: 16
  c_flipper_left_hold:
    number: 3208-2
    allow_enable: true
  c_flipper_right_main:
    number: 3208-5
    default_pulse_ms: 16
  c_flipper_right_hold:
    number: 3208-4
    allow_enable: true
  # c_flipper_top_right_main:
  #  number: #TODO
  #c_flipper_top_right_hold:
  #  number: #TODO
  #  allow_enable: true

playfields:
  playfield:
    tags: default
    default_source_device: None # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
#  top_right_flipper:
#    main_coil: c_flipper_top_right_main
#    hold_coil: c_flipper_top_right_hold
#    activation_switch: s_top_right_flipper
#    enable_events: machine_reset_phase_3
