#config_version=6


sequence_shots:
  left_orbit:
    switch_sequence: s_left_orbit, s_right_orbit
    sequence_timeout: 2s
  right_orbit:
    switch_sequence: s_right_orbit, s_left_orbit 
    sequence_timeout: 2s
  inner_orbit:
    switch_sequence: s_inner_orbit, s_right_orbit
    sequence_timeout: 2s