#config_version=6
sound_player:
  mode_base_started:
    Randomizer:
      action: play
      loops: -1
      bus: music
      fade_in: 300ms
  mode_base_stopped:
    Randomizer:
      action: stop
  mode_miked_started:
    Randomizer:
      action: stop
    makeSomeNoise:
      action: play
      loops: -1
      bus: music
      fade_in: 300ms
  mode_miked_stopped:
    makeSomeNoise:
      action: stop
    Randomizer:
      action: play
      loops: -1
      bus: music
      fade_in: 300ms
    
variable_player:
  increase_main_volume:
    fast_audio_main_volume:
      action: add_machine
      int: 1
  decrease_main_volume:
    fast_audio_main_volume:
      action: add_machine
      int: -1
  increase_sub_volume:
    fast_audio_sub_volume:
      action: add_machine
      int: 1
  decrease_sub_volume:
    fast_audio_sub_volume:
      action: add_machine
      int: -1
  increase_headphones_volume:
    fast_audio_headphones_volume:
      action: add_machine
      int: 1
  decrease_headphones_volume:
    fast_audio_headphones_volume:
      action: add_machine
      int: -1
