#config_version=6

switches:
  s_left_flipper:
    number: cab-8
    tags: left_flipper
  s_right_flipper:
    number: cab-9
    tags: right_flipper
  s_top_right_flipper:
    number: cab-10
    tags: top_right_flipper
  s_start:
    number: cab-11
    tags: start
  s_tilt_bob:
    number: cab-12
    tags: tilt_warning
  s_trough1:
    number: 3208-0
    type: NC
  s_trough2:
    number: 3208-1
  s_trough3:
    number: 3208-2
  s_trough4:
    number: 3208-3
  s_trough5:
    number: 3208-4
  s_trough6:
    number: 3208-5
  s_trough_jam:
    number: 3208-6
    type: NC
  s_plunger:
    number: 3208-7
    events_when_activated: ball_in
    events_when_deactivated: ball_out
  s_right_inlane:
    number: 3208-10
    tags: playfield_active
  s_left_inlane:
    number: 3208-14
    tags: playfield_active
  s_right_outlane:
    number: 3208-11
    tags: playfield_active
  s_left_outlane:
    number: 3208-13
    tags: playfield_active
  s_left_slingshot:
    number: 3208-15
  s_right_slingshot:
    number: 3208-9
  s_right_lower_pop:
    number: 0804-0
  s_captive_ball:
    number: 0804-1
    ignore_window_ms: 500
  s_pop_standup:
    number: 0804-6
  s_spinner:
    number: 0804-5
  s_three_bank_bottom:
    number: 0804-2
  s_three_bank_middle:
    number: 0804-3
  s_three_bank_top:
    number: 0804-4
  s_left_upper_pop:
    number: 0804b-0
  s_center_upper_pop:
    number: 0804b-1
  s_upper_pop_standup:
    number: 0804b-3
  s_scoop:
    number: 0804b-2
  s_tshirt_top_standup:
    number: 3208-23
  s_tshirt_bottom_standup:
    number: 3208-22
  s_three_bank_standup:
    number: 3208-21
  s_left_orbit:
    number: 0804b-4
  s_inner_orbit:
    number: 0804b-5
  s_left_ramp:
    number: 0804b-6
  s_right_ramp:
    number: 0804b-7
  s_right_orbit:
    number: 0804-7

drop_targets:
  bottom:
    switch: s_three_bank_bottom
  middle:
    switch: s_three_bank_middle
  top:
    switch: s_three_bank_top

drop_target_banks:
  three_bank:
    drop_targets: bottom, middle, top
    reset_coils: c_three_bank
    reset_on_complete: 20s

spinners:
  basic_spinner:
    switch: s_spinner

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6
