#config_version=6

#You can use variables to define different states and how they react. Please visit https://docs.missionpinball.org/en/latest/machine_vars/index.html

#machine_vars:
# diverter_state:
#   initial_value: 0
#   persist: false
#   value_type: int

player_vars:
  miked_timer:
    initial_value: 0
    value_type: int
  miked_count:
    initial_value: 0
    value_type: int
  brassmonkey_count:
    initial_value: 0
    value_type: int
  brassmonkey_modes_started:
    initial_value: 0
    value_type: int
  brassmonkey_multiplier:
    initial_value: 1
    value_type: int
  brassmonkey_shots:
    initial_value: 0
    value_type: int
