#config_version=6
##! mode: miked_setup_mode

mode:
  start_events: ball_started
  priority: 200

counters:
  miked_count:
    count_events: s_spinner_hit
    starting_count: 0
    count_complete_value: 10
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: miked_start
    debug: true
