#config_version=6
##! mode: miked_setup_mode

mode:
  start_events: ball_started
  priority: 200

counters:
  miked_counter:
    count_events: s_spinner_hit
    starting_count: 0
    count_complete_value: 10
    count_interval: 1
    direction: up
    persist_state: true
    events_when_complete: miked_start
    reset_on_complete: true
    debug: true

variable_player:
  logicblock_miked_counter_updated:
    miked_count_var:
      int: value
      action: set