#config_version=6

slide_player:
  mode_girls_started: girls

mode:
  start_events: girls_start
  stop_events: timer_girls_timer_complete
  priority: 300

config:
  - shots.yaml
  - variables_girls.yaml
  - sounds_girls.yaml

timers:
  girls_timer:
    start_value: 15
    end_value: 0
    direction: down
    control_events:
      - action: start
        event: mode_girls_started
