#config_version=6

sound_player:
  right_outlane_hit:
    girls_trim:
      action: play
  left_outlane_hit:
    girls_trim:
      action: play
  right_inlane_hit:
    girls_trim:
      action: play
  left_inlane_hit:
    girls_trim:
      action: play
  s_left_slingshot_active:
    girls_trim:
      action: play
  s_right_slingshot_active:
    girls_trim:
      action: play
  s_left_upper_pop_active:
    girls_trim:
      action: play
  s_center_upper_pop_active:
    girls_trim:
      action: play
  s_right_lower_pop_active:
    girls_trim:
      action: play
  captive_ball_hit:
    girls_trim:
      action: play
  pop_standup_hit:
    girls_trim:
      action: play
  upper_pop_standup_hit:
    girls_trim:
      action: play
  spinner_hit:
    girls_trim:
      action: play
  drop_target_bank_three_bank_down:
    girls_trim:
      action: play
  drop_target_bottom_down:
    girls_trim:
      action: play
  drop_target_middle_down:
    girls_trim:
      action: play
  drop_target_top_down:
    girls_trim:
      action: play
  scoop_hit:
    girls_trim:
      action: play
  tshirt_top_standup_hit:
    girls_trim:
      action: play
  tshirt_bottom_standup_hit:
    girls_trim:
      action: play
  three_bank_standup_hit:
    girls_trim:
      action: play
  left_orbit_hit:
    girls_trim:
      action: play
  right_orbit_hit:
    girls_trim:
      action: play
  inner_orbit_hit:
    girls_trim:
      action: play
  left_ramp_hit:
    girls_trim:
      action: play
  right_ramp_hit:
    girls_trim:
      action: play